### ISSUE TITLE
Packer (virtualbox-iso) sets HTTPIP to 10.0.2.2 but serves traffic on 10.0.2.3!

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-virtualbox#105]
_This issue was originally opened by @autumnjolitz in https://github.com/hashicorp/packer/issues/12298 and has been migrated to this repository. The original issue description is below._

---

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

The ip address provided at variable `HTTPIP` is incorrect. 

#### Reproduction Steps

1. `packer build cerberus-dragonfly.pkr.hcl`
2. wait for the VM to start and get to a shell
3. watch as it just hangs on `fetch`
4. Control-C out of it inside the vm and try `curl http://10.0.2.3/init.sh` instead

### Packer version
Packer v1.8.6

### Simplified Packer Template

https://github.com/autumnjolitz/cerberus_gateway/

### Operating system and Environment details

Mac OSX 11.4, x86-64
Packer version: 1.8.6 [go1.19.6 darwin amd64]

### Log Fragments and crash.log files

Log file: https://gist.github.com/autumnjolitz/276a5976ea085997ba0123e0df771069

**Comment by nareshsukhija** [comment]
Since https://github.com/hashicorp/packer/issues/12298 is locked/closed, it is not possible to add a comment there.

**Comment by nywilken** [comment]
Hi @autumnjolitz thanks for opening up this issue. The team and I have not been able to prioritize this work yet but I do understand how important it is to get it resolved. Would you or a member of the community be open taking a shot at opening  a PR with the fix? 

We can can help review and push the fix forward for sure.

**Comment by nywilken** [comment]
@nareshsukhija thanks for the bubbling up the issue again. The same offer to you if you would be interested in attempting to make a fix.

**Comment by nywilken** [comment]
Hey there apologies for the long delay on this issue. It looks like this particular issue was resolved by https://github.com/hashicorp/packer-plugin-virtualbox/pull/122 but the fix has not yet been released. 

I'm in the process of reviewing a few 7.0.x related issues and will get this change released as soon as possible.
